name: Build PDF

on: [push]

jobs:
    build:
        runs-on: debian:10.3

        steps:
        - uses: actions/checkout@v2

        - name: Build with Docker
          run: |
            docker build -t tex-builder .
            docker run --rm --user=$(id -u):$(id -g) -v "$PWD:/workspace" tex-builder \
              sh -c "pdflatex -interaction=nonstopmode -halt-on-error CV\cv.tex || (cat main.log && exit 1)"
            cat main.log

        - name: Upload PDF artifact
          if: success()
          uses: actions/upload-artifact@v2
          with:
            name: cv.pdf
            path: cv.pdf